#!/bin/bash

echo -e "\033[1;32mThis script is for testing purposes. Run \"sudo make install\" instead.\033[0m"

THIS=$(dirname -- "$(readlink -f -- "$0")")

make "PREFIX=$THIS/out" install

"$THIS/out/bin/transformers_ocr" "$@"
